### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ulfalizer** [RomaVis/pymenuconfig#1]
I just noticed this. Seems to work fine from some quick testing. :)

I have some freelancing for the Zephyr project coming up, which among other things includes making a `menuconfig`. They had a terminal interface in mind, but maybe TkInter would be fine too. Perhaps this could be used instead in that case.

Would you be fine with me linking this from the Kconfiglib page, or do you want to do more development first?

Here's two features that I think would be handy by the way:

 * Mouse support

 * A search feature that can jump to a particular location in the menu tree. It could search e.g. symbol names, prompts, and help texts. The C menuconfig uses `/` as the search key, but doesn't support jumping to a particular location.

One small nit (though it's probably just something you haven't implemented yet):
When you press ESC to go to the parent menu, it seems you always end up at the top of the menu rather than where you were previously.

Cheers and great work,
Ulf

**Comment by ulfalizer** [comment]
Ask if you have any questions btw.

**Comment by romavis** [comment]
Hey!

I appreciate placing a link to this project somewhere, and it would be cool if someone finds this useful. I would like to note that the code here is really a first version that was sketched pretty quickly. That says a lot about code style (there's no stable one), availability of docstrings and comments, and also app stability (it works, but hasn't been really field-tested).

In general, I want to continue further development of this project so I'm open for feature suggestions and bug reports.

> - Mouse support

Can you provide more details on how you think this should be implemented? I mean, what double click does, should there be any menus available through a right click, etc.

> - A search feature

I would look into this.

> When you press ESC to go to the parent menu, it seems you always end up at the top of the menu rather than where you were previously.

That's going to be fixed soon. Also you may've noticed that when menu listbox is refreshed, the selection is preserved not in a most elegant way (it shows you the previously selected node if it's still visible, but it can jump back and forth on the screen). I'm thinking how to improve that...

Thanks,
Roman

**Comment by ulfalizer** [comment]
> I appreciate placing a link to this project somewhere, and it would be cool if someone finds this useful. I would like to note that the code here is really a first version that was sketched pretty quickly. That says a lot about code style (there's no stable one), availability of docstrings and comments, and also app stability (it works, but hasn't been really field-tested).

I could always indicate that it's a work-in-progress next to the link.

> Mouse support
> Can you provide more details on how you think this should be implemented? I mean, what double click does, should there be any menus available through a right click, etc.

Being able to click on e.g. `[ ]` to toggle a symbol would be a good start I think.

Another option would be to have a single-click anywhere on a row toggle the symbol. That might be easier to implement if it's text-based, and seems pretty handy too.

You'd still need some way to enter menus in that case though. I was thinking double-click, but that would overlap with single-click I guess. Hmm...

A way to move back to the parent menu with the mouse would be handy too. Maybe middle-click would be a good fit. That leaves right-click open for e.g. menus.

> Also you may've noticed that when menu listbox is refreshed, the selection is preserved not in a most elegant way (it shows you the previously selected node if it's still visible, but it can jump back and forth on the screen). I'm thinking how to improve that...

Would be least surprising if the toggled entry always stays put I think. Maybe you could save its current row number, then set the new value, then check where the entry ends up in the list of symbols, and then scroll the listbox by the required amount so that it appears on the same row as before.

Another small thing I noticed btw: You can get the expanded main menu text via `Kconfig.mainmenu_text`. For the Linux kernel, you get `Linux/$ARCH $KERNELVERSION Kernel Configuration -> General setup` at the top now, without the variables expanded.

The C `menuconfig` just displays the expanded main menu text on a separate row (`Linux/x86 4.16.0-rc3 Kernel Configuration`), with e.g. `-> General setup -> IRQ subsystem` below it.

(Another tiny thing: Pressing `?` in the C `menuconfig` displays the help for the current entry.)

I might join in in development later. I have some features I want to add Kconfiglib first though (`savedefconfig` is the big one at the moment). :)

Cheers,
Ulf

**Comment by ulfalizer** [comment]
I've added some links prominently on the Kconfiglib GitHub page now.

Thanks!
